name: Package & Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - run: npm i
    - run: npm shrinkwrap
    - run: npm pack
    - run: npm pkg get version | xargs -I{} gh release create v{} ./*.tgz --generate-notes
