name: Manual Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "npm"
    - run: npm i
    - name: Pack a release
      run: |
        npm shrinkwrap
        npm pack
    - name: Set version
      run: echo "RELEASE_VERSION=v$(npm pkg get version | xargs)" >> $GITHUB_ENV
    - name: Print version
      run: echo $RELEASE_VERSION
    - name: Create a release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create $RELEASE_VERSION ./*.tgz --generate-notes
